name: Get the Unity version required from a Unity Project, expects a packageversion.txt file

on:
  workflow_call:
    inputs:
      runs-on:
        description: "JSON array of runner labels to determine the action runner to use, e.g. '[\"ubuntu-latest\", \"self-hosted\"]'"
        required: true
        type: string
      version-file-path:
        description: 'Optional, specify a path to search for the unity project version text file. Use this if validation fails to find a valid project version file.'
        type: string
        required: false
    outputs:
      unityversion:
        description: "Returns the version of Unity the UPM package requires"
        value: ${{ jobs.get_unity_version.outputs.upmunityversion }}

jobs:
  get_unity_version:
    name: Get required Unity version from Unity Project
    runs-on: ${{ fromJSON(inputs.runs-on) }}
    outputs:
      upmunityversion: ${{ steps.getversion.outputs.upmunityversion }}
    steps:
      - name: Script Version
        run: |
          echo "::group::Script Versioning"
          $scriptVersion = "1.0.3"
          echo "Build Script Version: $scriptVersion"
          echo "::endgroup::"
        shell: pwsh
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          clean: true
      - id: getversion
        name: 'Get Unity Package Version'
        run: |
          echo "::group::Validating input"

          $versionFile = "${{ inputs.version-file-path }}"
          if([string]::IsNullOrEmpty($versionFile))
          {
            echo 'version input was empty, using default'
            $versionFile = '**/ProjectSettings/ProjectVersion.txt'
          }

          if ( -not (Test-Path -Path $versionFile) ) {
            Write-Error "Failed to find a valid ProjectVersion.txt file"
            exit 1
          }

          echo "::endgroup::"

          echo "::group::Unity Version Project check"

          $version = Get-Content $versionFile
          $pattern = '(?<version>(?:(?<major>\d+)\.)?(?:(?<minor>\d+)\.)?(?:(?<patch>\d+[fab]\d+)\b))|((?:\((?<revision>\w+))\))'
          $matches = $matches = [regex]::Matches($version, $pattern)
          $unityVersion = $matches[1].Groups['version'].Value.Trim()
        
          echo "Detected version is $unityVersion"
          echo "upmunityversion=$unityVersion" >> $env:GITHUB_OUTPUT
          echo "::endgroup::"

        shell: pwsh